### ISSUE TITLE
elcalc 5.0 Roadmap

### ISSUE THREAD

**Issue by xxczaki** [elcalc/elcalc#4]
### High Priority:

- [x] Write basic tests with Spectron.
- [x] Full code cleanup.
- [x] Replace `eval` with `math.eval` from math.js.
- [x] Fix UI on Windows. 
- [x] Handle uncaught exceptions.
- [x] Do not use `element.innerHTML`.
- [x] Make the <kbd>.</kbd> key work. 
- [x] Fix numpad bug [#6]. _**in progress**_
- [ ] Website!
- [ ] Sign Code.

### Medium Priority:

- [x]  Use CSS style linter.
- [x]  Simplify build script.
- [x]  Use some kind of logger.
- [x] Make UI look better on macOS.
- [x]  Add keyboard support.
- [x]  Add live reload for better development.

### Low Priority:

- [x] Make readme.md look better.

---

Pull requests & suggestions are welcome 🚀👍❤️

**Comment by liberodark** [comment]
Hi,
Please add keyboard support !
Thx !

**Comment by xxczaki** [comment]
@liberodark thanks for your suggestion, I added it to the project roadmap :smile:

**Comment by liberodark** [comment]
Add have send your soft on AUR :D

**Comment by liberodark** [comment]
Please add in you roadmap more options for avanced calculator (scientist)

**Comment by xxczaki** [comment]
Thank you once again, I added your suggestion to the project roadmap 😃

**Comment by xxczaki** [comment]
@liberodark I'm not sure about adding more advanced features to this calculator, cause it was originally made to be simple 😕
